
package presentacion;

import java.awt.Canvas;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSlider;


public class Vista extends javax.swing.JFrame {

    private final Modelo modelo;
    private Controlador control;
 
    public Vista(Modelo m) {
        modelo = m;
        initComponents();
        capturarEventos();        
    }

    public Modelo getModelo() {
        return modelo;
    }

    public Controlador getControl() {
        if(control == null){
            control = new Controlador(this);
        }
        return control;
    }

    public JButton getBtnAnimar() {
        return btnAnimar;
    }

    public Canvas getLienzo() {
        return lienzo;
    }

    public JSlider getSliBolitas() {
        return sliBolitas;
    }

    public JLabel getLblMensaje() {
        return lblMensaje;
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAnimar = new javax.swing.JButton();
        lienzo = new java.awt.Canvas();
        sliBolitas = new javax.swing.JSlider();
        lblMensaje = new javax.swing.JLabel();
        caja = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Número de bolitas a animar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 40, 220, 40);

        btnAnimar.setText("Iniciar");
        getContentPane().add(btnAnimar);
        btnAnimar.setBounds(20, 190, 230, 120);

        lienzo.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lienzo);
        lienzo.setBounds(270, 20, 790, 520);

        sliBolitas.setMajorTickSpacing(1);
        sliBolitas.setMaximum(10);
        sliBolitas.setMinorTickSpacing(1);
        sliBolitas.setPaintLabels(true);
        sliBolitas.setPaintTicks(true);
        sliBolitas.setValue(2);
        getContentPane().add(sliBolitas);
        sliBolitas.setBounds(20, 90, 220, 80);
        getContentPane().add(lblMensaje);
        lblMensaje.setBounds(20, 320, 230, 50);

        caja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bola 1", "Bola 2", "Bola 3", "Bola 4", "Bola 5", "Bola 6", "Bola 7", "Bola 8", "Bola 9", "Bola 10" }));
        getContentPane().add(caja);
        caja.setBounds(80, 400, 107, 35);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimar;
    private javax.swing.JComboBox<String> caja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMensaje;
    private java.awt.Canvas lienzo;
    private javax.swing.JSlider sliBolitas;
    // End of variables declaration//GEN-END:variables

    private void capturarEventos() {
        btnAnimar.addActionListener(getControl());
        caja.addActionListener(getControl());
    }

    public JComboBox<String> getCaja() {
        return caja;
    }
}
